#####################################
# GENERAL PARAMETERS                #
#####################################
#species: ''                               # OPTIONAL: ENTER VALUE for genome version, see 'genomes' dictionary below, e.g., hg38.
genome_dir: '/path/to/genomes'             # ENTER VALUE for genome_dir: path to "root" directory containing sub-directory for each species
snakemake:
    path: '/path/to/snakemake/program'     # ENTER VALUE for the snakemake v7.16.1 command (including path, or modules to load)
    parameters: ''                         # Additional Snakemake parameters, e.g. '--dry-run --notemp'
singularity:
    prefix: 'singularity-images'           # ENTER VALUE for the folder where images should be stored for re-use (typically a central location)
pipeline: bksnake                          # (do not change) Type of pipeline: bksnake (bulk RNAseq) or vcsnake (variant calling) pipeline. Currently only  "bksnake" is supported !


###############################
# COMMONLY CHANGED PARAMETERS #
###############################
results: output                             # ENTER VALUE for the folder name of output files ("result" files)
metadata:
    file: resources/test-data/metadata.txt  # ENTER VALUE for the metadata file
    group_name: GROUP                       # ENTER VALUE matching the input metdata file (one of the column names)

# Optional parameters for output files generation and storage:
# In order to generate and/or keep those files set either 'True' or 'False' (default)
#annotations: ['refseq','ensembl'] # use this list to specify which annotations should be processed, see "genomes: db" parameter below, default: all annotations will be processed
keep_fastq_files: False         # whether to keep the downloaded fastq files in the results folder, default: False
keep_bam_files: False           # whether to keep intermediate bam files in the results folder, default: False
keep_vcf_files: False           # whether to keep the vcf files from the crosscheck fingerprint analysis, default: False
generate_cram_files: False      # whether to generate and keep final cram files, default: False
generate_bw_files: False        # whether to generate and keep final bw files (read coverage bigwig files), default: False
generate_unmapped: False        # whether to generate and keep unmapped read files, default: False
junction_annotation: False      # whether to generate junction annotations with RSEQC package, default: False
crosscheck_fingerprints: False  # whether to perform Picard's 'CrosscheckFingerprints' metrics, only for organism=Homo sapiens, default: False


# Cutadapt, read trimming
# -a adapter   Sequence of an adapter ligated to the 3' end (paired data: of the first read).
# -A ADAPTER   3' adapter to be removed from R2
# Below are the default Illumina universal parameters
# For optional parameters, see cutadapt manual: https://cutadapt.readthedocs.io/en/stable/guide.html#basic-usage
# Normally, trimming is not required (see https://academic.oup.com/nargab/article/2/3/lqaa068/5901066 )
cutadapt:
    run: False  # switch to perform or not cutadapt trimming, default: 'False'
    parameters: '-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --minimum-length 10'


####################################
# LESS COMMONLY CHANGED PARAMETERS #
####################################
# Specify featureCounts parameters except -s, -a, -T, -o, as these are already specified in the corresponding rule
featurecounts:
    parameters: '-Q 10 -B -C --minOverlap 10 --fracOverlap 0.2 -t exon -g gene_id'


# infer_experiments strandness parameter, see: https://rseqc.sourceforge.net/#infer-experiment-py
strandness_mode: auto # auto, fr or ff

# STAR read mapping parameters
star_threads: 12
star_version: star_2.7.11b  # required for STAR_DIR variable
# Additional parameters for STAR, except the following as they are already used in the rule:
# --runThreadN, --genomeDir, --outFileNamePrefix, --outTmpDir, --sjdbGTFfile, --outSAMtype, --readFilesCommand, --outReadsUnmapped, --outSAMattrRGline, --readFilesIn 
star:
    params: "--outTmpKeep All --outSAMmapqUnique 60 --outSAMattributes All"


#####################################
# REFERENCE GENOMES AND ANNOTATIONS #
#####################################
# genome_dir: path to "root" directory containing sub-directory for each species (is specified above)
# genomes: genome_subdir: sub-directory name under the "root" directory
overrule_organism: False # if True then parameter 'species' can over rule parameter 'organism' (e.g. map monkey data onto human genome)
genomes:
    hg38: { species: 'hg38', species_name: 'human', organism: 'Homo sapiens', genome_subdir: 'hg38', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'XIST', 'DDX3Y'], db: ['refseq', 'ensembl', 'gencode'], default: False }
    chm13: { species: 'chm13', species_name: 'human', organism: 'Homo sapiens', genome_subdir: 'chm13', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'XIST', 'DDX3Y'], db: ['refseq'], default: False }
    mfa5: { species: 'mfa5', species_name: 'cyno', organism: 'Macaca fascicularis', genome_subdir: 'mfa5', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq', 'ensembl'], default: False }
    mfa6: { species: 'mfa6', species_name: 'cyno', organism: 'Macaca fascicularis', genome_subdir: 'mfa6', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq'], default: False }
    mm10: { species: 'mm10', species_name: 'mouse', organism: 'Mus musculus', genome_subdir: 'mm10', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Xist', 'Ddx3y'], db: ['refseq', 'ensembl', 'gencode'], default: False }
    mm39: { species: 'mm39', species_name: 'mouse', organism: 'Mus musculus', genome_subdir: 'mm39', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Xist', 'Ddx3y'], db: ['refseq', 'ensembl', 'gencode'], default: False }
    rn6: { species: 'rn6', species_name: 'rat', organism: 'Rattus norvegicus', genome_subdir: 'rn6', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Ddx3x', 'Ddx3y'], db: ['refseq', 'ensembl'], default: False }
    rn7: { species: 'rn7', species_name: 'rat', organism: 'Rattus norvegicus', genome_subdir: 'rn7', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Ddx3x', 'Ddx3y'], db: ['refseq', 'ensembl'], default: False }
    ss11: { species: 'ss11', species_name: 'pig', organism: 'Sus scrofa', genome_subdir: 'ss11', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq', 'ensembl'], default: False }
    oc2: { species: 'oc2', species_name: 'rabbit', organism: 'Oryctolagus cuniculus', genome_subdir: 'oc2', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq', 'ensembl'], default: False }
    CriGri_PICRH_1_0: { species: 'CriGri_PICRH_1_0', species_name: 'hamster', organism: 'Cricetulus griseus', genome_subdir: 'CriGri_PICRH_1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v104', 'ensembl_v111', 'ensembl_v112'], default: True }
    GRCh38p14: { species: 'GRCh38p14', species_name: 'human', organism: 'Homo sapiens', genome_subdir: 'GRCh38p14', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'XIST', 'DDX3Y'], db: ['refseq_vRS_2023_10', 'gencode_v45', 'ensembl_v112', 'ensembl_v111'], default: True }
    GRCm38p6: { species: 'GRCm38p6', species_name: 'mouse', organism: 'Mus musculus', genome_subdir: 'GRCm38p6', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Xist', 'Ddx3y'], db: ['ensembl_v102'], default: True}
    GRCm39: { species: 'GRCm39', species_name: 'mouse', organism: 'Mus musculus', genome_subdir: 'GRCm39', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Xist', 'Ddx3y'], db: ['refseq_vRS_2024_02', 'gencode_vM34', 'ensembl_v112', 'ensembl_v111'] }
    GRCr8: { species: 'GRCr8', species_name: 'rat', organism: 'Rattus norvegicus', genome_subdir: 'GRCr8', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Ddx3x', 'Ddx3y'], db: ['refseq_vRS_2024_02'], default: True }
    Macaca_fascicularis_5_0: { species: 'Macaca_fascicularis_5_0', species_name: 'cyno', organism: 'Macaca fascicularis', genome_subdir: 'Macaca_fascicularis_5_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v101', 'ensembl_v102'], default: False }
    MFA1912RKSv2: { species: 'MFA1912RKSv2', species_name: 'cyno', organism: 'Macaca fascicularis', genome_subdir: 'MFA1912RKSv2', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v102'], default: True }
    Mmul_10: { species: 'Mmul_10', species_name: 'rhesus', organism: 'Macaca mulatta', genome_subdir: 'Mmul_10', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v103', 'ensembl_v112'], default: True }
    mRatBN7_2: { species: 'mRatBN7_2', species_name: 'rat', organism: 'Rattus norvegicus', genome_subdir: 'mRatBN7_2', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Ddx3x', 'Ddx3y'], db: ['refseq_v108', 'ensembl_v112', 'ensembl_v109'], default: False }
    OryCun2_0: { species: 'OryCun2_0', species_name: 'rabbit', organism: 'Oryctolagus cuniculus', genome_subdir: 'OryCun2_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v102', 'ensembl_v112', 'ensembl_v109'], default: True }
    Rnor_6_0: { species: 'Rnor_6_0', species_name: 'rat', organism: 'Rattus norvegicus', genome_subdir: 'Rnor_6_0', biokitr_genes: ['Gapdh', 'Rps28', 'Actb', 'Ddx3x', 'Ddx3y'], db: ['refseq_v106', 'ensembl_v104'], default: False }
    ROS_Cfam_1_0: { species: 'ROS_Cfam_1_0', species_name: 'dog', organism: 'Canis lupus', genome_subdir: 'ROS_Cfam_1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v106', 'ensembl_v112'], default: True }
    Sscrofa11_1: { species: 'Sscrofa11_1', species_name: 'pig', organism: 'Sus scrofa', genome_subdir: 'Sscrofa11_1', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v106', 'ensembl_v112', 'ensembl_v109'], default: True }
    T2T_CHM13v2_0: { species: 'T2T_CHM13v2_0', species_name: 'human', organism: 'Homo sapiens', genome_subdir: 'T2T_CHM13v2_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'XIST', 'DDX3Y'], db: ['refseq_vRS_2023_10'], default: False }
    T2T_MFA8v1_0: { species: 'T2T_MFA8v1_0', species_name: 'cyno', organism: 'Macaca fascicularis', genome_subdir: 'T2T_MFA8v1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_vRS_2024_05'], default: False }
    UM_NZW_1_0: { species: 'UM_NZW_1_0', species_name: 'rabbit', organism: 'Oryctolagus cuniculus', genome_subdir: 'UM_NZW_1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_vRS_2023_02'], default: False }
    UU_Cfam_GSD_1_0: { species: 'UU_Cfam_GSD_1_0', species_name: 'dog', organism: 'Canis lupus', genome_subdir: 'UU_Cfam_GSD_1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v106'], default: False }
    Vero_WHO_p1_0: { species: 'Vero_WHO_p1_0', species_name: 'green_monkey', organism: 'Chlorocebus sabaeus', genome_subdir: 'Vero_WHO_p1_0', biokitr_genes: ['GAPDH', 'RPS28', 'ACTB', 'DDX3X'], db: ['refseq_v102'], default: True }


#########################################
# ORGANISM NAMES AND TRANSLATIONS       # all in lower case
#########################################
translations:
  Homo sapiens:
    - human
    - homo sapiens
  Mus musculus:
    - mouse
    - mus musculus
  Rattus norvegicus:
    - rat
    - rattus norvegicus
  Canis familiaris:
    - dog
    - canis lupus
    - canis lupus familiaris
  Sus scrofa:
    - pig
    - sus scrofa
  Macaca fascicularis:
    - cyno
    - cyno monkey
    - cynomolgus
    - cynomolgus monkey
    - macaca fascicularis
  Macaca mulatta:
    - rhesus
    - rhesus monkey
    - macaca mulatta
  Chlorocebus sabaeus:
    - green
    - green monkey
    - african green monkey
    - chlorocebus sabaeus
  Oryctolagus cuniculus:
    - rabbit
    - oryctolagus cuniculus
  Cricetulus griseus:
    - hamster
    - chinese hamster
    - cricetulus griseus


#########################################
# REFERENCE GENOMES RELATIVE FILE PATHS # do not change
#########################################
# stable file names
ref_fasta: 'fasta/genome.fa'
ref_fasta_gz: 'fasta/genome.fa.gz'
ref_fasta_fai: 'fasta/genome.fa.gz.fai'
ref_fasta_gzi: 'fasta/genome.fa.gz.gzi'
genome_dict: 'fasta/genome.dict'
genome_size: 'fasta/genome.chrom.sizes'
ribo_intervals: 'fasta/genome.rRNA_intervals'


####################################
# PUBLIC DOMAIN SINGULARITY IMAGES # do not change
####################################
# Image from Galaxy Depot
BAMTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/bamtools%3A2.5.2--hdcf5f25_2'
BCFTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/bcftools%3A1.13--h3a49de5_0' 
#BCFTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/bcftools%3A1.19--h8b25389_0' ### THIS VERSION MAKES PROBLEMS IN THE CONCATENATE STEP OF VCSNAKE
BEDOPS_IMAGE: 'https://depot.galaxyproject.org/singularity/bedops%3A2.4.41--h9f5acd7_0'
BEDSORT_IMAGE: 'https://depot.galaxyproject.org/singularity/ucsc-bedsort%3A377--ha8a8165_4'
BEDTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/bedtools%3A2.31.1--hf5e1c6e_0'
BWA_IMAGE: 'https://depot.galaxyproject.org/singularity/bwa%3A0.7.17--he4a0461_11'
CUTADAPT_IMAGE: 'https://depot.galaxyproject.org/singularity/cutadapt%3A4.6--py39hf95cd2a_1'
DEEPTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/deeptools%3A3.5.4--pyhdfd78af_1'
FASTQC_IMAGE: 'https://depot.galaxyproject.org/singularity/fastqc%3A0.12.1--hdfd78af_0'
GATK_IMAGE: 'https://depot.galaxyproject.org/singularity/gatk4%3A4.0.0.0--py36_0'
GENEPREDTOBED_IMAGE: 'https://depot.galaxyproject.org/singularity/ucsc-genepredtobed%3A447--h954228d_0'
GTFTOGENEPRED_IMAGE: 'https://depot.galaxyproject.org/singularity/ucsc-gtftogenepred%3A447--h954228d_0'
JAVA_IMAGE: 'https://depot.galaxyproject.org/singularity/java-jdk:8.0.112--0'
JBROWSE2_IMAGE: 'https://depot.galaxyproject.org/singularity/jbrowse2%3A2.10.2--hd6180af_0'
JQ_IMAGE: 'https://depot.galaxyproject.org/singularity/jq%3A1.6'
MULTIQC_IMAGE: 'https://depot.galaxyproject.org/singularity/multiqc%3A1.21--pyhdfd78af_0'
PICARD_IMAGE: 'https://depot.galaxyproject.org/singularity/picard-slim%3A3.1.1--hdfd78af_0'
RSEQC_IMAGE: 'https://depot.galaxyproject.org/singularity/rseqc%3A5.0.3--py39hf95cd2a_0'
SAMTOOLS_IMAGE: 'https://depot.galaxyproject.org/singularity/samtools%3A1.19.2--h50ea8bc_0'
STAR_IMAGE: 'https://depot.galaxyproject.org/singularity/star%3A2.7.11b--h43eeafb_0' 
SUBREAD_IMAGE: 'https://depot.galaxyproject.org/singularity/subread%3A2.0.6--he4a0461_0'  ### Introduction of new parameter --countReadPairs
TABIX_IMAGE: 'https://depot.galaxyproject.org/singularity/tabix:0.2.6--ha92aebf_0'
VEP_IMAGE: 'https://depot.galaxyproject.org/singularity/ensembl-vep%3A111.0--pl5321h2a3209d_0'

# Other images
NGSTOOLS_IMAGE: 'docker://ghcr.io/bedapub/ngs-tools:main'
RIBIOSSCRIPTS_IMAGE: 'docker://ghcr.io/bedapub/ribiosscripts:main'
