###############################
# COMMONLY CHANGED PARAMETERS #
###############################

results: 'output'
metadata_file: 'resources/test-data/metadata.txt'
metadata_group_name: 'GROUP'

# Optional parameters for output files generation and storage:
# In order to generate and/or keep those files set either 'True' or 'False' (default)
keep_fastq_files: True    # whether to keep the downloaded fastq files in the results folder, default 'False'
keep_bam_files: True      # whether to keep intermediate bam files in the results folder, default 'False'
generate_cram_files: True  # whether to generate and keep final cram files, default 'True'
generate_bw_files: True   # whether to generate and keep final bw files (read coverage bigwig files), default: 'True'
generate_unmapped: True   # whether to generate and keep unmapped read files, default: 'False'

# Cutadapt, read trimming
# -a adapter   Sequence of an adapter ligated to the 3' end (paired data: of the first read).
# -A ADAPTER   3' adapter to be removed from R2
# Below are the default Illumina universal parameters
# For optional parameters, see cutadapt manual: https://cutadapt.readthedocs.io/en/stable/guide.html#basic-usage
# Normally, trimming is not required (see https://academic.oup.com/nargab/article/2/3/lqaa068/5901066 )
cutadapt:
        run: False  # switch to perform or not cutadapt trimming, default: 'False'
        parameters: '-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT --minimum-length 10'
