latency-wait: "5"
jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "False"
restart-times: "0"
jobs: "3000"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "30"
max-status-checks-per-second: "0.005"
